"""Add location

Revision ID: 655f8f557073
Revises: ea4aacb4a27e
Create Date: 2025-10-19 13:59:03.553667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '655f8f557073'
down_revision: Union[str, Sequence[str], None] = 'ea4aacb4a27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'location')
    # ### end Alembic commands ###
