"""Add tags field to blogpost

Revision ID: ea4aacb4a27e
Revises: b1e1364d30c3
Create Date: 2025-10-19 13:23:55.894155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ea4aacb4a27e'
down_revision: Union[str, Sequence[str], None] = 'b1e1364d30c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogpost', sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogpost', 'tags')
    # ### end Alembic commands ###
